//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeNotebooks.Texts {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class T {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal T() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SafeNotebooks.Texts.T", typeof(T).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string _in {
            get {
                return ResourceManager.GetString("in", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        internal static string SelectAndNew {
            get {
                return ResourceManager.GetString("SelectAndNew", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Notebook {
            get {
                return ResourceManager.GetString("Notebook", resourceCulture);
            }
        }
        
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        internal static string Notebooks {
            get {
                return ResourceManager.GetString("Notebooks", resourceCulture);
            }
        }
        
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        internal static string NewNotebook {
            get {
                return ResourceManager.GetString("NewNotebook", resourceCulture);
            }
        }
        
        internal static string NewPage {
            get {
                return ResourceManager.GetString("NewPage", resourceCulture);
            }
        }
        
        internal static string SearchQueryPlaceholder {
            get {
                return ResourceManager.GetString("SearchQueryPlaceholder", resourceCulture);
            }
        }
        
        internal static string AuthenticateDeviceOwnerReason {
            get {
                return ResourceManager.GetString("AuthenticateDeviceOwnerReason", resourceCulture);
            }
        }
        
        internal static string IsLocked {
            get {
                return ResourceManager.GetString("IsLocked", resourceCulture);
            }
        }
        
        internal static string PinPlaceholder {
            get {
                return ResourceManager.GetString("PinPlaceholder", resourceCulture);
            }
        }
        
        internal static string WhereStoreNotebook {
            get {
                return ResourceManager.GetString("WhereStoreNotebook", resourceCulture);
            }
        }
        
        internal static string HowToSort {
            get {
                return ResourceManager.GetString("HowToSort", resourceCulture);
            }
        }
        
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        internal static string SortByColor {
            get {
                return ResourceManager.GetString("SortByColor", resourceCulture);
            }
        }
        
        internal static string SortByName {
            get {
                return ResourceManager.GetString("SortByName", resourceCulture);
            }
        }
        
        internal static string SortByDate {
            get {
                return ResourceManager.GetString("SortByDate", resourceCulture);
            }
        }
    }
}
